- hosts:  
  tasks:
    - package:
        name: httpd
        state: present
    - file:
        path: '/root/Menu/index.html'
        state: touch
    - copy:
        content: 'hii its arpit here'
        dest: '/root/Menu/index.html'
    - copy:
        src: '/root/Menu/index.html'
        dest: '/var/www/html/'
    - service:
        name: httpd
        state: started
        enabled: yes
    - service:
        name: firewalld
        state: stopped
