FROM  	website
CMD    /usr/sbin/firefox


#RUN  yum install -y httpd
#ADD  httpd.conf  /etc/httpd/conf/httpd.conf

#RUN  mkdir  -p /var/www/html
#ADD  index.html   /var/www/html/index.html

#EXPOSE  80

#CMD     ["httpd","-g","deamon off;"]

