- hosts: web
  tasks:
    - package:
        name: httpd
        state: present
    - file:
        path: '../files/index.html'
        state: touch
    - copy:
        content: 'hii its arpit here'
        dest: '../files/index.html'
    - copy:
        src: '../files/index.html'
        dest: '/var/www/html/'
    - service:
        name: httpd
        state: started
        enabled: yes
    - firewalld:
        state: enabled
        port: "80/tcp"
        immediate: yes
        permanent: yes
