- hosts: all
  tasks:
    - package: 
        name: nginx
        state: present
    - service:
        name: nginx
        state: started 
        enabled: yes
    - firewalld: 
        state: enabled
        port: 80/tcp
        immediate: yes
        permanent: yes
